language: r
sudo: required

r_build_args: --no-build-vignettes --no-manual --no-resave-data

r_check_args: --no-build-vignettes --no-manual --timings --as-cran

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"

r_binary_packages:
  - testthat

branches:
  only:
    - master

notifications:
  email:
    recipients:
    - landon.sego@pnnl.gov
    on_success: change
    on_failure: change
